eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOST:http://localhost:8761/eureka}  # URL del servidor Eureka donde se registrará el Config Server
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

server:
  port: ${CUSTOM.SERVER.PORT:9030}

spring:
  application:
    name: alumno-service
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/sistema_alumno?authSource=admin